import Vue from 'vue'
import * as directives from 'vuetify/es5/directives'
import {
  Vuetify,
  VApp,
  VNavigationDrawer,
  VFooter,
  VList,
  VBtn,
  VIcon,
  VGrid,
  VToolbar,
  VCard,
  transitions,
  VForm,
  VTextField,
  VMenu,
  VDatePicker,
  VRadioGroup,
  VSnackbar,
  VTabs,
  VDialog,
  VChip,
  VProgressCircular,
  VProgressLinear,
  VSpeedDial,
  VImg,
  VTextarea,
  VAutocomplete,
  VAvatar,
  VTooltip
} from 'vuetify'
import 'vuetify/src/stylus/app.styl'

Vue.use(Vuetify, {
  components: {
    Vuetify,
    VApp,
    VNavigationDrawer,
    VFooter,
    VList,
    VBtn,
    VIcon,
    VGrid,
    VToolbar,
    VCard,
    transitions,
    VForm,
    VTextField,
    VMenu,
    VDatePicker,
    VRadioGroup,
    VSnackbar,
    VTabs,
    VDialog,
    VChip,
    VProgressCircular,
    VProgressLinear,
    VSpeedDial,
    VImg,
    VTextarea,
    VAutocomplete,
    VAvatar,
    VTooltip
  },
  directives,
  theme: {
    primary: '#553F75',
    secondary: '#A21010',
    accent: '#553F75',
    error: '#FF5252',
    info: '#2196F3',
    success: '#4CAF50',
    warning: '#FFC107'
  },
})
